/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.labapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

import org.threeten.bp.OffsetDateTime;

/**
 * AppInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-29T14:56:43.172-07:00")
public class AppInfo {
  @SerializedName("objectId")
  private String objectId = null;

  @SerializedName("appType")
  private String appType = null;

  @SerializedName("resourceAppId")
  private String resourceAppId = null;

  @SerializedName("signInAudience")
  private String signInAudience = null;

  @SerializedName("appName")
  private String appName = null;

  @SerializedName("appId")
  private String appId = null;

  @SerializedName("redirectUri")
  private String redirectUri = null;

  @SerializedName("authority")
  private String authority = null;

  @SerializedName("defaultScopes")
  private String defaultScopes = null;

  @SerializedName("identifierUris")
  private String identifierUris = null;

  @SerializedName("homePage")
  private String homePage = null;

  @SerializedName("multiTenantApp")
  private String multiTenantApp = null;

  @SerializedName("appRoles")
  private String appRoles = null;

  @SerializedName("labName")
  private String labName = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("lastUpdatedDate")
  private String lastUpdatedDate = null;

  public AppInfo objectId(String objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Get objectId
   * @return objectId
  **/
  @ApiModelProperty(value = "")
  public String getObjectId() {
    return objectId;
  }

  public void setObjectId(String objectId) {
    this.objectId = objectId;
  }

  public AppInfo appType(String appType) {
    this.appType = appType;
    return this;
  }

   /**
   * Get appType
   * @return appType
  **/
  @ApiModelProperty(value = "")
  public String getAppType() {
    return appType;
  }

  public void setAppType(String appType) {
    this.appType = appType;
  }

  public AppInfo resourceAppId(String resourceAppId) {
    this.resourceAppId = resourceAppId;
    return this;
  }

   /**
   * Get resourceAppId
   * @return resourceAppId
  **/
  @ApiModelProperty(value = "")
  public String getResourceAppId() {
    return resourceAppId;
  }

  public void setResourceAppId(String resourceAppId) {
    this.resourceAppId = resourceAppId;
  }

  public AppInfo signInAudience(String signInAudience) {
    this.signInAudience = signInAudience;
    return this;
  }

   /**
   * Get signInAudience
   * @return signInAudience
  **/
  @ApiModelProperty(value = "")
  public String getSignInAudience() {
    return signInAudience;
  }

  public void setSignInAudience(String signInAudience) {
    this.signInAudience = signInAudience;
  }

  public AppInfo appName(String appName) {
    this.appName = appName;
    return this;
  }

   /**
   * Get appName
   * @return appName
  **/
  @ApiModelProperty(value = "")
  public String getAppName() {
    return appName;
  }

  public void setAppName(String appName) {
    this.appName = appName;
  }

  public AppInfo appId(String appId) {
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @ApiModelProperty(value = "")
  public String getAppId() {
    return appId;
  }

  public void setAppId(String appId) {
    this.appId = appId;
  }

  public AppInfo redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Get redirectUri
   * @return redirectUri
  **/
  @ApiModelProperty(value = "")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public AppInfo authority(String authority) {
    this.authority = authority;
    return this;
  }

   /**
   * Get authority
   * @return authority
  **/
  @ApiModelProperty(value = "")
  public String getAuthority() {
    return authority;
  }

  public void setAuthority(String authority) {
    this.authority = authority;
  }

  public AppInfo defaultScopes(String defaultScopes) {
    this.defaultScopes = defaultScopes;
    return this;
  }

   /**
   * Get defaultScopes
   * @return defaultScopes
  **/
  @ApiModelProperty(value = "")
  public String getDefaultScopes() {
    return defaultScopes;
  }

  public void setDefaultScopes(String defaultScopes) {
    this.defaultScopes = defaultScopes;
  }

  public AppInfo identifierUris(String identifierUris) {
    this.identifierUris = identifierUris;
    return this;
  }

   /**
   * Get identifierUris
   * @return identifierUris
  **/
  @ApiModelProperty(value = "")
  public String getIdentifierUris() {
    return identifierUris;
  }

  public void setIdentifierUris(String identifierUris) {
    this.identifierUris = identifierUris;
  }

  public AppInfo homePage(String homePage) {
    this.homePage = homePage;
    return this;
  }

   /**
   * Get homePage
   * @return homePage
  **/
  @ApiModelProperty(value = "")
  public String getHomePage() {
    return homePage;
  }

  public void setHomePage(String homePage) {
    this.homePage = homePage;
  }

  public AppInfo multiTenantApp(String multiTenantApp) {
    this.multiTenantApp = multiTenantApp;
    return this;
  }

   /**
   * Get multiTenantApp
   * @return multiTenantApp
  **/
  @ApiModelProperty(value = "")
  public String getMultiTenantApp() {
    return multiTenantApp;
  }

  public void setMultiTenantApp(String multiTenantApp) {
    this.multiTenantApp = multiTenantApp;
  }

  public AppInfo appRoles(String appRoles) {
    this.appRoles = appRoles;
    return this;
  }

   /**
   * Get appRoles
   * @return appRoles
  **/
  @ApiModelProperty(value = "")
  public String getAppRoles() {
    return appRoles;
  }

  public void setAppRoles(String appRoles) {
    this.appRoles = appRoles;
  }

  public AppInfo labName(String labName) {
    this.labName = labName;
    return this;
  }

   /**
   * Get labName
   * @return labName
  **/
  @ApiModelProperty(value = "")
  public String getLabName() {
    return labName;
  }

  public void setLabName(String labName) {
    this.labName = labName;
  }

  public AppInfo lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(value = "")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public AppInfo lastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

   /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
  **/
  @ApiModelProperty(value = "")
  public String getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppInfo appInfo = (AppInfo) o;
    return Objects.equals(this.objectId, appInfo.objectId) &&
        Objects.equals(this.appType, appInfo.appType) &&
        Objects.equals(this.resourceAppId, appInfo.resourceAppId) &&
        Objects.equals(this.signInAudience, appInfo.signInAudience) &&
        Objects.equals(this.appName, appInfo.appName) &&
        Objects.equals(this.appId, appInfo.appId) &&
        Objects.equals(this.redirectUri, appInfo.redirectUri) &&
        Objects.equals(this.authority, appInfo.authority) &&
        Objects.equals(this.defaultScopes, appInfo.defaultScopes) &&
        Objects.equals(this.identifierUris, appInfo.identifierUris) &&
        Objects.equals(this.homePage, appInfo.homePage) &&
        Objects.equals(this.multiTenantApp, appInfo.multiTenantApp) &&
        Objects.equals(this.appRoles, appInfo.appRoles) &&
        Objects.equals(this.labName, appInfo.labName) &&
        Objects.equals(this.lastUpdatedBy, appInfo.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedDate, appInfo.lastUpdatedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectId, appType, resourceAppId, signInAudience, appName, appId, redirectUri, authority, defaultScopes, identifierUris, homePage, multiTenantApp, appRoles, labName, lastUpdatedBy, lastUpdatedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppInfo {\n");
    
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    appType: ").append(toIndentedString(appType)).append("\n");
    sb.append("    resourceAppId: ").append(toIndentedString(resourceAppId)).append("\n");
    sb.append("    signInAudience: ").append(toIndentedString(signInAudience)).append("\n");
    sb.append("    appName: ").append(toIndentedString(appName)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    defaultScopes: ").append(toIndentedString(defaultScopes)).append("\n");
    sb.append("    identifierUris: ").append(toIndentedString(identifierUris)).append("\n");
    sb.append("    homePage: ").append(toIndentedString(homePage)).append("\n");
    sb.append("    multiTenantApp: ").append(toIndentedString(multiTenantApp)).append("\n");
    sb.append("    appRoles: ").append(toIndentedString(appRoles)).append("\n");
    sb.append("    labName: ").append(toIndentedString(labName)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

