/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.labapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * TempUserInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-29T14:56:43.172-07:00")
public class TempUserInfo {
  @SerializedName("title")
  private String title = null;

  @SerializedName("upn")
  private String upn = null;

  @SerializedName("groupAssignment")
  private String groupAssignment = null;

  @SerializedName("accountLifeSpanInMinutes")
  private String accountLifeSpanInMinutes = null;

  @SerializedName("currentTime")
  private String currentTime = null;

  @SerializedName("createdTime")
  private String createdTime = null;

  public TempUserInfo title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public TempUserInfo upn(String upn) {
    this.upn = upn;
    return this;
  }

   /**
   * Get upn
   * @return upn
  **/
  @ApiModelProperty(value = "")
  public String getUpn() {
    return upn;
  }

  public void setUpn(String upn) {
    this.upn = upn;
  }

  public TempUserInfo groupAssignment(String groupAssignment) {
    this.groupAssignment = groupAssignment;
    return this;
  }

   /**
   * Get groupAssignment
   * @return groupAssignment
  **/
  @ApiModelProperty(value = "")
  public String getGroupAssignment() {
    return groupAssignment;
  }

  public void setGroupAssignment(String groupAssignment) {
    this.groupAssignment = groupAssignment;
  }

  public TempUserInfo accountLifeSpanInMinutes(String accountLifeSpanInMinutes) {
    this.accountLifeSpanInMinutes = accountLifeSpanInMinutes;
    return this;
  }

   /**
   * Get accountLifeSpanInMinutes
   * @return accountLifeSpanInMinutes
  **/
  @ApiModelProperty(value = "")
  public String getAccountLifeSpanInMinutes() {
    return accountLifeSpanInMinutes;
  }

  public void setAccountLifeSpanInMinutes(String accountLifeSpanInMinutes) {
    this.accountLifeSpanInMinutes = accountLifeSpanInMinutes;
  }

  public TempUserInfo currentTime(String currentTime) {
    this.currentTime = currentTime;
    return this;
  }

   /**
   * Get currentTime
   * @return currentTime
  **/
  @ApiModelProperty(value = "")
  public String getCurrentTime() {
    return currentTime;
  }

  public void setCurrentTime(String currentTime) {
    this.currentTime = currentTime;
  }

  public TempUserInfo createdTime(String createdTime) {
    this.createdTime = createdTime;
    return this;
  }

   /**
   * Get createdTime
   * @return createdTime
  **/
  @ApiModelProperty(value = "")
  public String getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(String createdTime) {
    this.createdTime = createdTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TempUserInfo tempUserInfo = (TempUserInfo) o;
    return Objects.equals(this.title, tempUserInfo.title) &&
        Objects.equals(this.upn, tempUserInfo.upn) &&
        Objects.equals(this.groupAssignment, tempUserInfo.groupAssignment) &&
        Objects.equals(this.accountLifeSpanInMinutes, tempUserInfo.accountLifeSpanInMinutes) &&
        Objects.equals(this.currentTime, tempUserInfo.currentTime) &&
        Objects.equals(this.createdTime, tempUserInfo.createdTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, upn, groupAssignment, accountLifeSpanInMinutes, currentTime, createdTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TempUserInfo {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    upn: ").append(toIndentedString(upn)).append("\n");
    sb.append("    groupAssignment: ").append(toIndentedString(groupAssignment)).append("\n");
    sb.append("    accountLifeSpanInMinutes: ").append(toIndentedString(accountLifeSpanInMinutes)).append("\n");
    sb.append("    currentTime: ").append(toIndentedString(currentTime)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

