/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.labapi.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

import org.threeten.bp.OffsetDateTime;

/**
 * UserInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-29T14:56:43.172-07:00")
public class UserInfo {
  @SerializedName("appId")
  private String appId = null;

  @SerializedName("objectId")
  private String objectId = null;

  @SerializedName("userType")
  private String userType = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("licenses")
  private String licenses = null;

  @SerializedName("upn")
  private String upn = null;

  @SerializedName("mfa")
  private String mfa = null;

  @SerializedName("protectionPolicy")
  private String protectionPolicy = null;

  @SerializedName("homeDomain")
  private String homeDomain = null;

  @SerializedName("homeUPN")
  private String homeUPN = null;

  @SerializedName("b2cProvider")
  private String b2cProvider = null;

  @SerializedName("guestHomedIn")
  private String guestHomedIn = null;

  @SerializedName("labName")
  private String labName = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("lastUpdatedDate")
  private String lastUpdatedDate = null;

  public UserInfo appId(String appId) {
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @ApiModelProperty(value = "")
  public String getAppId() {
    return appId;
  }

  public void setAppId(String appId) {
    this.appId = appId;
  }

  public UserInfo objectId(String objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Get objectId
   * @return objectId
  **/
  @ApiModelProperty(value = "")
  public String getObjectId() {
    return objectId;
  }

  public void setObjectId(String objectId) {
    this.objectId = objectId;
  }

  public UserInfo userType(String userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @ApiModelProperty(value = "")
  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  public UserInfo displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public UserInfo licenses(String licenses) {
    this.licenses = licenses;
    return this;
  }

   /**
   * Get licenses
   * @return licenses
  **/
  @ApiModelProperty(value = "")
  public String getLicenses() {
    return licenses;
  }

  public void setLicenses(String licenses) {
    this.licenses = licenses;
  }

  public UserInfo upn(String upn) {
    this.upn = upn;
    return this;
  }

   /**
   * Get upn
   * @return upn
  **/
  @ApiModelProperty(value = "")
  public String getUpn() {
    return upn;
  }

  public void setUpn(String upn) {
    this.upn = upn;
  }

  public UserInfo mfa(String mfa) {
    this.mfa = mfa;
    return this;
  }

   /**
   * Get mfa
   * @return mfa
  **/
  @ApiModelProperty(value = "")
  public String getMfa() {
    return mfa;
  }

  public void setMfa(String mfa) {
    this.mfa = mfa;
  }

  public UserInfo protectionPolicy(String protectionPolicy) {
    this.protectionPolicy = protectionPolicy;
    return this;
  }

   /**
   * Get protectionPolicy
   * @return protectionPolicy
  **/
  @ApiModelProperty(value = "")
  public String getProtectionPolicy() {
    return protectionPolicy;
  }

  public void setProtectionPolicy(String protectionPolicy) {
    this.protectionPolicy = protectionPolicy;
  }

  public UserInfo homeDomain(String homeDomain) {
    this.homeDomain = homeDomain;
    return this;
  }

   /**
   * Get homeDomain
   * @return homeDomain
  **/
  @ApiModelProperty(value = "")
  public String getHomeDomain() {
    return homeDomain;
  }

  public void setHomeDomain(String homeDomain) {
    this.homeDomain = homeDomain;
  }

  public UserInfo homeUPN(String homeUPN) {
    this.homeUPN = homeUPN;
    return this;
  }

   /**
   * Get homeUPN
   * @return homeUPN
  **/
  @ApiModelProperty(value = "")
  public String getHomeUPN() {
    return homeUPN;
  }

  public void setHomeUPN(String homeUPN) {
    this.homeUPN = homeUPN;
  }

  public UserInfo b2cProvider(String b2cProvider) {
    this.b2cProvider = b2cProvider;
    return this;
  }

   /**
   * Get b2cProvider
   * @return b2cProvider
  **/
  @ApiModelProperty(value = "")
  public String getB2cProvider() {
    return b2cProvider;
  }

  public void setB2cProvider(String b2cProvider) {
    this.b2cProvider = b2cProvider;
  }

  public UserInfo guestHomedIn(String guestHomedIn) {
    this.guestHomedIn = guestHomedIn;
    return this;
  }

  /**
   * Get guestHomedIn
   * @return guestHomedIn
   **/
  @ApiModelProperty(value = "")
  public String getGuestHomedIn() {
    return guestHomedIn;
  }

  public void setGuestHomedIn(String guestHomedIn) {
    this.guestHomedIn = guestHomedIn;
  }

  public UserInfo labName(String labName) {
    this.labName = labName;
    return this;
  }

   /**
   * Get labName
   * @return labName
  **/
  @ApiModelProperty(value = "")
  public String getLabName() {
    return labName;
  }

  public void setLabName(String labName) {
    this.labName = labName;
  }

  public UserInfo lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(value = "")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public UserInfo lastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

   /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
  **/
  @ApiModelProperty(value = "")
  public String getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfo userInfo = (UserInfo) o;
    return Objects.equals(this.appId, userInfo.appId) &&
        Objects.equals(this.objectId, userInfo.objectId) &&
        Objects.equals(this.userType, userInfo.userType) &&
        Objects.equals(this.displayName, userInfo.displayName) &&
        Objects.equals(this.licenses, userInfo.licenses) &&
        Objects.equals(this.upn, userInfo.upn) &&
        Objects.equals(this.mfa, userInfo.mfa) &&
        Objects.equals(this.protectionPolicy, userInfo.protectionPolicy) &&
        Objects.equals(this.homeDomain, userInfo.homeDomain) &&
        Objects.equals(this.homeUPN, userInfo.homeUPN) &&
        Objects.equals(this.b2cProvider, userInfo.b2cProvider) &&
        Objects.equals(this.labName, userInfo.labName) &&
        Objects.equals(this.lastUpdatedBy, userInfo.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedDate, userInfo.lastUpdatedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, objectId, userType, displayName, licenses, upn, mfa, protectionPolicy, homeDomain, homeUPN, b2cProvider, labName, lastUpdatedBy, lastUpdatedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    licenses: ").append(toIndentedString(licenses)).append("\n");
    sb.append("    upn: ").append(toIndentedString(upn)).append("\n");
    sb.append("    mfa: ").append(toIndentedString(mfa)).append("\n");
    sb.append("    protectionPolicy: ").append(toIndentedString(protectionPolicy)).append("\n");
    sb.append("    homeDomain: ").append(toIndentedString(homeDomain)).append("\n");
    sb.append("    homeUPN: ").append(toIndentedString(homeUPN)).append("\n");
    sb.append("    b2cProvider: ").append(toIndentedString(b2cProvider)).append("\n");
    sb.append("    labName: ").append(toIndentedString(labName)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

