/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.identity.internal.test.labapi.api;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.model.AppInfo;
import com.microsoft.identity.internal.test.labapi.model.CustomErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppApi
 */
@Ignore
public class AppApiTest {

    private final AppApi api = new AppApi();

    /**
     * Gets App Info based on App ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiAppAppidGetTest() throws ApiException {
        String appid = null;
        List<AppInfo> response = api.apiAppAppidGet(appid);

        // TODO: test validations
    }
    /**
     * Gets App Info based on Azure Environment or Sign-in Audience
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiAppGetTest() throws ApiException {
        String apptype = null;
        String appplatform = null;
        String azureenvironment = null;
        String signinaudience = null;
        String isadminconsented = null;
        String publicclient = null;
        List<AppInfo> response = api.apiAppGet(apptype, appplatform, azureenvironment, signinaudience, isadminconsented, publicclient);

        // TODO: test validations
    }
}
