/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.microsoft.identity.internal.test.labapi.api;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.model.ConfigInfo;
import com.microsoft.identity.internal.test.labapi.model.CustomErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigApi
 */
@Ignore
public class ConfigApiTest {

    private final ConfigApi api = new ConfigApi();

    /**
     * Gets the Lab Configurartion (User/App/Lab) Based on Query Parameters with predefined defaults.   You can override the defaults.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiConfigGetTest() throws ApiException {
        String usertype = null;
        String userrole = null;
        String mfa = null;
        String protectionpolicy = null;
        String homedomain = null;
        String homeupn = null;
        String b2cprovider = null;
        String federationprovider = null;
        String azureenvironment = null;
        String guesthomeazureenvironment = null;
        String apptype = null;
        String appplatform = null;
        String publicclient = null;
        String signinaudience = null;
        String guesthomedin = null;
        String hasaltid = null;
        String altidsource = null;
        String altidtype = null;
        String passwordpolicyvalidityperiod = null;
        String passwordpolicynotificationdays = null;
        String tokenlifetimepolicy = null;
        String tokentype = null;
        String tokenlifetime = null;
        String isadminconsented = null;
        String optionalclaim = null;
        List<ConfigInfo> response = api.apiConfigGet(usertype, userrole, mfa, protectionpolicy, homedomain, homeupn, b2cprovider, federationprovider, azureenvironment, guesthomeazureenvironment, apptype, appplatform, publicclient, signinaudience, guesthomedin, hasaltid, altidsource, altidtype, passwordpolicyvalidityperiod, passwordpolicynotificationdays, tokenlifetimepolicy, tokentype, tokenlifetime, isadminconsented, optionalclaim);

        // TODO: test validations
    }
    /**
     * Gets a single Lab User Config with Lab and App Info based on UPN
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiConfigUpnGetTest() throws ApiException {
        String upn = null;
        List<ConfigInfo> response = api.apiConfigUpnGet(upn);

        // TODO: test validations
    }
}
