/**
 * // Copyright (c) Microsoft Corporation.
 * // All rights reserved.
 * //
 * // This code is licensed under the MIT License.
 * //
 * // Permission is hereby granted, free of charge, to any person obtaining a copy
 * // of this software and associated documentation files(the "Software"), to deal
 * // in the Software without restriction, including without limitation the rights
 * // to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
 * // copies of the Software, and to permit persons to whom the Software is
 * // furnished to do so, subject to the following conditions :
 * //
 * // The above copyright notice and this permission notice shall be included in
 * // all copies or substantial portions of the Software.
 * //
 * // THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * // IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * // FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * // AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * // LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * // OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * // THE SOFTWARE.
 * */

/*
 * KeyVaultClient
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.keyvault.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Details of the organization of the certificate issuer.
 */
@ApiModel(description = "Details of the organization of the certificate issuer.")
public class OrganizationDetails {
  @SerializedName("id")
  private String id = null;

  @SerializedName("admin_details")
  private List<AdministratorDetails> adminDetails = null;

  public OrganizationDetails id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the organization.
   * @return id
  **/
  @ApiModelProperty(value = "Id of the organization.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OrganizationDetails adminDetails(List<AdministratorDetails> adminDetails) {
    this.adminDetails = adminDetails;
    return this;
  }

  public OrganizationDetails addAdminDetailsItem(AdministratorDetails adminDetailsItem) {
    if (this.adminDetails == null) {
      this.adminDetails = new ArrayList<AdministratorDetails>();
    }
    this.adminDetails.add(adminDetailsItem);
    return this;
  }

   /**
   * Details of the organization administrator.
   * @return adminDetails
  **/
  @ApiModelProperty(value = "Details of the organization administrator.")
  public List<AdministratorDetails> getAdminDetails() {
    return adminDetails;
  }

  public void setAdminDetails(List<AdministratorDetails> adminDetails) {
    this.adminDetails = adminDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationDetails organizationDetails = (OrganizationDetails) o;
    return Objects.equals(this.id, organizationDetails.id) &&
        Objects.equals(this.adminDetails, organizationDetails.adminDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, adminDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationDetails {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    adminDetails: ").append(toIndentedString(adminDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

