# File: azure-pipelines\vsts-releases\common4j.yml
# Description: Publish common4j to internal feed
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: self
    type: git
    ref: master

jobs:
- template: ../templates/steps/vsts-release/vsts-release-template.yml
  parameters:
    project: common4j
    envVstsMvnAndroidAccessTokenVar: ENV_VSTS_MVN_CRED_ACCESSTOKEN
    assembleTask: assemble
    publishTask: publish
    sbomConfiguration: runtimeClasspath
    spotbugsCwdRoot: $(Build.SourcesDirectory)/common-java-root
    spotbugsCommand: spotbugsMain
