/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.testutils.lab;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.api.CreateTempUserApi;
import com.microsoft.identity.internal.test.labapi.model.TempUser;

import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for CreateTempUserApi
 */
@Ignore
public class CreateTempUserApiTest {

    private final CreateTempUserApi api = new CreateTempUserApi();

    
    /**
     * Let&#39;s you create a temp (a.k.a LOCKED USER) CLOUD User for testing purposes.   All users created by this API will be auto-deleted after 90 minutes.
     *
     * You can create the following type of cloud users.        1. Basic : Account can be used for all manual testing including password resets, etc      2. GLOBALMFA : User with Global MFA      3. MFAONSPO : User requires MFA on a specific resource and the resource is SharePoint      4. MFAONEXO : User requires MFA on a specific resource and the resource is Exchange Online      5. MAMCA : User requires MAM on SharePoint      6. MDMCA : User requires MDM on SharePoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postTest() throws ApiException {
        String usertype = "basic";
        TempUser response = api.post(usertype);

        Assert.assertEquals(usertype, response.getUserType());
    }
    
}
