/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.testutils.lab;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.api.DeleteDeviceApi;
import com.microsoft.identity.internal.test.labapi.model.CustomSuccessResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DeleteDeviceApi
 */
@Ignore
public class DeleteDeviceApiTest {

    private final DeleteDeviceApi api = new DeleteDeviceApi();

    
    /**
     * Delete&#39;s a Device from AAD.   You need to provide the UPN and the Device ID (in GUID format) in Query String.
     *
     * Provides generic error messages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        String upn = null;
        String deviceid = null;
        CustomSuccessResponse response = api.delete(upn, deviceid);

        // TODO: test validations
    }
    
}
