/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.testutils.lab;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.api.DisablePolicyApi;
import com.microsoft.identity.internal.test.labapi.model.CustomSuccessResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DisablePolicyApi
 */
@Ignore
public class DisablePolicyApiTest {

    private final DisablePolicyApi api = new DisablePolicyApi();

    
    /**
     * lets you disable CA/Special Policies for any Locked User
     *
     * Disable Policy can be used for GlobalMFA, MAMCA, MDMCA, MFAONSPO, MFAONEXO.   Also test users can have more than 1 policy assigned to the same user.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putTest() throws ApiException {
        String upn = null;
        String policy = null;
        CustomSuccessResponse response = api.put(upn, policy);

        // TODO: test validations
    }
    
}
