/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.testutils.lab;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.api.LabUserSecretApi;
import com.microsoft.identity.internal.test.labapi.model.SecretResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for LabUserSecretApi
 */
@Ignore
public class LabUserSecretApiTest {

    private final LabUserSecretApi api = new LabUserSecretApi();

    
    /**
     * Gets the Lab User Secret from Identity Labs User Secret KeyVault.   You need to provide the secret in Query String.
     *
     * If not found it will return the KeyVault providers generic error message &#39;not found&#39;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLabUserSecretTest() throws ApiException {
        String secret = null;
        SecretResponse response = api.getLabUserSecret(secret);

        // TODO: test validations
    }
    
}
