/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.testutils.lab;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.api.ResetApi;
import com.microsoft.identity.internal.test.labapi.model.CustomSuccessResponse;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for ResetApi
 */
@Ignore
public class ResetApiTest {

    private final ResetApi api = new ResetApi();

    
    /**
     * Resets MFA/Password for a lab test user based on UPN.   You need to provide the UPN and Operation(MFA/Password) in Query String.
     *
     * Provides generic error messages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putResetInfoTest() throws ApiException {
        String upn = null;
        String operation = null;
        CustomSuccessResponse response = api.putResetInfo(upn, operation);

        // TODO: test validations
    }
    
}
