/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.testutils.lab;

import com.microsoft.identity.internal.test.labapi.ApiException;
import com.microsoft.identity.internal.test.labapi.api.TempUserInfoApi;
import com.microsoft.identity.internal.test.labapi.model.TempUserInfo;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for TempUserInfoApi
 */
@Ignore
public class TempUserInfoApiTest {

    private final TempUserInfoApi api = new TempUserInfoApi();

    
    /**
     * Let&#39;s you query for Locked Users and get user specific details.
     *
     * When you create temporary user, it gets created with \&quot;Locked_\&quot; in it&#39;s name so we can delete the account in 90 minutes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTempUserInfoTest() throws ApiException {
        String upn = null;
        TempUserInfo response = api.getTempUserInfo(upn);

        // TODO: test validations
    }
    
}
