/*
 * KeyVaultClient
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.keyvault;


public class Configuration {
    private static ApiClient defaultApiClient = new ApiClient();
    private static ApiClient buildAutomationApiClient = new ApiClient(ApiClient.BUILD_AUTOMATION_VAULT_BASE_PATH);

    /**
     * Get the default API client, which would be used when creating API
     * instances without providing an API client. The URL for this client
     * is ApiClient.DEFAULT_BASE_PATH, i.e. the default msidlabs KeyVault.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }

    /**
     * The URL for this client is ApiClient.BUILD_AUTOMATION_VAULT_BASE_PATH,
     * i.e. the MobileBuildVault KeyVault.
     *
     * @return API client
     */
    public static ApiClient getMobileBuildAutomationVaultApiClient() {
        return buildAutomationApiClient;
    }

    /**
     * Set the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @param apiClient API client
     */
    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient = apiClient;
    }
}
