# File: azure-pipelines\templates\steps\spotbugs.yml
# Description: Tasks to run Spotbugs (Assemble task must run first)
# https://github.com/AzureAD/android-complete/blob/master/plugins/buildsystem/docs/Spotbugs.md

parameters:
- name: project
- name: spotbugsCommand
  default: spotbugsLocalDebug
- name: artifactName
  default: CodeAnalysisLogs
- name: cwd
  default: $(Build.SourcesDirectory)
- name: javaVersion
  default: "1.21"
steps:
- bash: |
    echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
    echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
  displayName: 'Set VSTS Fields in Environment'
- task: Gradle@3
  displayName: 'Run Spotbugs'
  inputs:
    javaHomeSelection: JDKVersion
    jdkVersionOption: ${{parameters.javaVersion}}
    jdkArchitecture: x64
    cwd: ${{ parameters.cwd }}
    tasks: ${{ parameters.project }}:${{ parameters.spotbugsCommand }}
    publishJUnitResults: false
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: SpotBugs'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/${{ parameters.project }}/build/reports/spotbugs'
    ArtifactName: ${{ parameters.artifactName }}
  condition: failed()
