/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CustomErrorResponse;
import io.swagger.client.model.CustomSuccessResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EnablePolicyApi
 */
@Ignore
public class EnablePolicyApiTest {

    private final EnablePolicyApi api = new EnablePolicyApi();

    /**
     * lets you enable CA/Special Policies for any Locked User
     *
     * Enable Policy can be used for GlobalMFA, MAMCA, MDMCA, MFAONSPO, MFAONEXO.   Also test users can have more than 1 policy assigned to the same user.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEnablePolicyPutTest() throws ApiException {
        String upn = null;
        String policy = null;
        CustomSuccessResponse response = api.apiEnablePolicyPut(upn, policy);

        // TODO: test validations
    }
}
