/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CustomErrorResponse;
import io.swagger.client.model.LabAvailability;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LabAvailabilityApi
 */
@Ignore
public class LabAvailabilityApiTest {

    private final LabAvailabilityApi api = new LabAvailabilityApi();

    /**
     * Will give you the current status of the labs
     *
     * Query this when a test fails to see if the failure is because of a lab. If so retry after sometime
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiLabAvailabilityGetTest() throws ApiException {
        List<LabAvailability> response = api.apiLabAvailabilityGet();

        // TODO: test validations
    }
}
