/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CustomErrorResponse;
import io.swagger.client.model.SecretResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LabUserSecretApi
 */
@Ignore
public class LabUserSecretApiTest {

    private final LabUserSecretApi api = new LabUserSecretApi();

    /**
     * Use LabSecret EndPoint Instead of this. This will be deprecated end of March 2020  You need to provide the secret in Query String.
     *
     * If not found it will return the KeyVault providers generic error message &#x27;not found&#x27;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiLabUserSecretGetTest() throws ApiException {
        String secret = null;
        SecretResponse response = api.apiLabUserSecretGet(secret);

        // TODO: test validations
    }
}
