/*
 * Azure Identity Labs API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CustomErrorResponse;
import io.swagger.client.model.CustomSuccessResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResetApi
 */
@Ignore
public class ResetApiTest {

    private final ResetApi api = new ResetApi();

    /**
     * Resets MFA/Password for a lab test user based on UPN.   You need to provide the UPN and Operation(MFA/Password) in Query String.
     *
     * Provides generic error messages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiResetPutTest() throws ApiException {
        String upn = null;
        String operation = null;
        CustomSuccessResponse response = api.apiResetPut(upn, operation);

        // TODO: test validations
    }
}
