# Description: Template to build & publish any auth client android sdk library to internal maven feed

parameters:
- name: prBranchReportArtifact
  default: jacocoReport
- name: devBranchReportArtifact
  default: jacocoReportDev
# List of stages this templates depends on to start.
- name: dependsOn
  type: object
  default: []

stages:
- stage: compare_coverage
  displayName: Compare Code Coverage
  dependsOn:
    - build_and_test
  jobs:
    - job: compare
      displayName: PR VS. Dev
      continueOnError: true
      steps:
        - checkout: self
          clean: true
          submodules: recursive
          persistCredentials: True
        - download: current
          artifact: ${{ parameters.prBranchReportArtifact }} # Adjust artifact name as needed
        - download: current
          artifact: ${{ parameters.devBranchReportArtifact }} # Adjust artifact name as needed
        - script: |
            python $(Build.SourcesDirectory)/azure-pipelines/code-coverage/compare_coverage.py $(Pipeline.Workspace)/jacocoReport/jacocoTestReport.xml $(Pipeline.Workspace)/jacocoReportDev/jacocoTestReport.xml
          displayName: Compare Jacoco Coverage