package com.microsoft.identity.common.internal.providers.microsoft.microsoftsts;

import com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectoryAuthorizationRequest;

public class MicrosoftStsAuthorizationRequest extends AzureActiveDirectoryAuthorizationRequest {}
