# File: azure-pipelines\pull-request-validation\build-consumers.yml
# Description: Test new common in ADAL / MSAL / Broker (assembleLocal and testLocalDebugUnitTest)
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
# Variable: 'commonBranchName' common branch to be used when running the pipeline manually
# Variable: 'skipConsumerValidationLabel' PR label used to skip the checks in this pipeline
name: $(date:yyyyMMdd)$(rev:.r)

parameters:
  - name: shouldSkipLongRunningTest
    displayName: Should skip long running test?
    type: boolean
    default: true

variables:
- name: shouldSkipLongRunningTest
  ${{ if parameters.shouldSkipLongRunningTest }}:
    value: "-PshouldSkipLongRunningTest"
  ${{ else }}:
    value: ""
- name: robolectricSdkVersion
  value: 28
- group: AndroidAuthClientAutomationSecrets
- group: MSIDLABVARS
- group: devex-ciam-test

resources:
  repositories:
  - repository: msal
    type: github
    name: AzureAD/microsoft-authentication-library-for-android
    ref: dev
    endpoint: ANDROID_GITHUB
  - repository: broker
    type: github
    name: identity-authnz-teams/ad-accounts-for-android
    ref: dev
    endpoint: github-inside-microsoft

stages:
- stage: getLabel
  # Check PR Label
  displayName: Check for PR Label
  pool:
    vmImage: 'windows-2022'
  jobs:
    - template: ../templates/steps/fetch-pr-labels.yml
- stage: validateConsumers
  # Validate Consumers
  displayName: 'Validate'
  dependsOn: getLabel
  pool:
    vmImage: 'windows-2022'
  variables:
    prLabels: $[ stageDependencies.getLabel.getLabelsJob.outputs['fetchPrCILabel.prLabels'] ]
  jobs:
  # setup
  - job: setupBranch
    displayName: Setup branch
    condition: and( succeeded(), not(contains(variables['prLabels'], variables['skipConsumerValidationLabel'])) )
    steps:
    - checkout: none
    - task: PowerShell@2
      name: setvarStep
      displayName: Set var branch
      inputs:
        targetType: inline
        script: |
          $branch = switch ( '$(Build.Reason)' )
          {
              PullRequest
              {
                '$(System.PullRequest.SourceBranch)'
              }
              Manual
              {
                '$(commonBranchName)'
              }
              default
              {
                ''
              }
          }
          Write-Output "$branch"
          echo "##vso[task.setvariable variable=commonBranch;isOutput=true]$branch"
    - powershell: |
        if ("$(setvarStep.commonBranch)" -eq "") {
          Write-Output "commonBranchName is not set using default common"
        }
        else{
          Write-Output "Using common branch $(setvarStep.commonBranch) in consumers"
        }
      name: echovar
      displayName: Echo branch name
  # msal
  - job: msalValidation
    displayName: MSAL
    dependsOn:
      - setupBranch
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
    condition: and( succeeded(), not(contains(variables['prLabels'], variables['skipConsumerValidationLabel'])) )
    steps:
    - checkout: msal
      displayName: Checkout msal repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - bash: |
        echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
        echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
      displayName: 'Set VSTS Fields in Environment'
    - task: Gradle@3
      displayName: Assemble msal
      inputs:
        jdkArchitecture: x64
        jdkVersionOption: "1.17"
        tasks: clean msal:assembleLocal
    - template: ../templates/steps/automation-cert.yml
    - task: Gradle@3
      displayName: Run msal Unit tests
      inputs:
        tasks: msal:testLocalDebugUnitTest -Plabtest -PlabSecret=$(LabVaultAppCert) -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PmockApiUrl=$(MOCK_API_URL) -PnativeAuthConfigString=$(NATIVE_AUTH_CONFIG_STRING)
        jdkArchitecture: x64
        jdkVersionOption: "1.17"
  # msalautomationapp
  - job: msalAutomationAppValidation
    displayName: MSAL Automation App
    dependsOn:
      - setupBranch
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
    condition: and( succeeded(), not(contains(variables['prLabels'], variables['skipConsumerValidationLabel'])) )
    steps:
    - checkout: msal
      displayName: Checkout msal repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - template: ../templates/steps/automation-cert.yml
    - task: Gradle@3
      displayName: Assemble msalautomationapp
      inputs:
        jdkArchitecture: x64
        jdkVersionOption: "1.17"
        tasks: clean msalautomationapp:assembleLocal
  # broker
  - job: brokerValidation
    displayName: Broker
    cancelTimeoutInMinutes: 1
    timeoutInMinutes: 120
    dependsOn:
      - setupBranch
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
    condition: and( succeeded(), not(contains(variables['prLabels'], variables['skipConsumerValidationLabel'])) )
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    steps:
    - checkout: broker
      displayName: Checkout broker repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - bash: |
        echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_USERNAME]VSTS"
        echo "##vso[task.setvariable variable=ENV_VSTS_MVN_CRED_ACCESSTOKEN]$(System.AccessToken)"
      displayName: 'Set VSTS Fields in Environment'
    - template: ../templates/steps/automation-cert.yml
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: Gradle@3
      displayName: Assemble broker
      inputs:
        tasks: AADAuthenticator:clean AADAuthenticator:assembleLocal --build-cache --info
        publishJUnitResults: false
        jdkArchitecture: x64
        jdkVersionOption: "1.17"
    - task: Gradle@3
      displayName: Run broker Unit tests
      inputs:
        tasks: AADAuthenticator:localDebugAADAuthenticatorUnitTestCoverageReport --build-cache --info -Plabtest -PlabSecret=$(LabVaultAppCert) -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PpowerLiftApiKey=$(powerliftApiKey) -PcodeCoverageEnabled=true ${{variables.shouldSkipLongRunningTest}}
        jdkArchitecture: x64
        jdkVersionOption: "1.17"
  # brokerautomationapp
  - job: brokerAutomationAppValidation
    displayName: Broker Automation App
    cancelTimeoutInMinutes: 1
    timeoutInMinutes: 120
    dependsOn:
      - setupBranch
    variables:
      commonBranch: $[ dependencies.setupBranch.outputs['setvarStep.commonBranch'] ]  # map in the variable
    condition: and( succeeded(), not(contains(variables['prLabels'], variables['skipConsumerValidationLabel'])) )
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    steps:
    - checkout: broker
      displayName: Checkout broker repository
      clean: true
      submodules: recursive
      persistCredentials: True
    - template: ../templates/steps/automation-cert.yml
    - task: CmdLine@2
      displayName: Checkout common submodule $(commonBranch)
      inputs:
        script: |
          git fetch
          git checkout $(commonBranch)
          git pull
          git status
          git rev-parse HEAD
        workingDirectory: $(Agent.BuildDirectory)/s/common
    - task: Gradle@3
      displayName: Assemble brokerautomationapp
      inputs:
        tasks: brokerautomationapp:clean brokerautomationapp:assembleLocal --build-cache --info
        publishJUnitResults: false
        jdkArchitecture: x64
        jdkVersionOption: "1.17"
