# Description: Run instrumented test for Common.
name: Instrumented Tests

parameters:
  # Name of the git project we want to checkout.
  - name: androidAPILevel
    displayName: Android Api Level
    default: 30

resources:
  repositories:
    - repository: AuthClientAndroidPipelines
      type: git
      name: Engineering/AuthClientAndroidPipelines
      ref: fadi/monthly-discovery

stages:
  - stage: 'runInstrumentedTests'
    displayName: Instrumented Tests
    jobs:
      - template: templates/runTests/run-instrumented-tests.yml@AuthClientAndroidPipelines
        parameters:
          gitProject: self
          projectName: common
          androidAPILevel: ${{ parameters.androidAPILevel }}
          accessTokenKey: ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN
          gradleOptions: -Psugar=true -PlabSecret=/data/local/tmp/LabAuth.pfx
          continueOnError: True
          useUbuntuLatest: True
