# File: azure-pipelines\auth-client\msal-instrumented-test.yml
# Description: Run instrumented test for Common.
name: Instrumented Tests

resources:
  repositories:
    - repository: AuthClientAndroidPipelines
      type: git
      name: Engineering/AuthClientAndroidPipelines
      ref: fadi/monthly-discovery

stages:
  - stage: 'runInstrumentedTests'
    displayName: Instrumented Tests
    jobs:
      - template: templates/runTests/run-instrumented-tests.yml@AuthClientAndroidPipelines
        parameters:
          gitProject: self
          projectName: common
          accessTokenKey: ENV_VSTS_MVN_ANDROIDADACCOUNTS_ACCESSTOKEN
          gradleOptions: -Psugar=true -PlabSecret=/data/local/tmp/LabAuth.pfx
          continueOnError: True
          useUbuntuLatest: True
